/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Organizer } from "./Organizer";
import { OrganizerCountArgs } from "./OrganizerCountArgs";
import { OrganizerFindManyArgs } from "./OrganizerFindManyArgs";
import { OrganizerFindUniqueArgs } from "./OrganizerFindUniqueArgs";
import { CreateOrganizerArgs } from "./CreateOrganizerArgs";
import { UpdateOrganizerArgs } from "./UpdateOrganizerArgs";
import { DeleteOrganizerArgs } from "./DeleteOrganizerArgs";
import { OrganizerService } from "../organizer.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Organizer)
export class OrganizerResolverBase {
  constructor(
    protected readonly service: OrganizerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Organizer",
    action: "read",
    possession: "any",
  })
  async _organizersMeta(
    @graphql.Args() args: OrganizerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Organizer])
  @nestAccessControl.UseRoles({
    resource: "Organizer",
    action: "read",
    possession: "any",
  })
  async organizers(
    @graphql.Args() args: OrganizerFindManyArgs
  ): Promise<Organizer[]> {
    return this.service.organizers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Organizer, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Organizer",
    action: "read",
    possession: "own",
  })
  async organizer(
    @graphql.Args() args: OrganizerFindUniqueArgs
  ): Promise<Organizer | null> {
    const result = await this.service.organizer(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Organizer)
  @nestAccessControl.UseRoles({
    resource: "Organizer",
    action: "create",
    possession: "any",
  })
  async createOrganizer(
    @graphql.Args() args: CreateOrganizerArgs
  ): Promise<Organizer> {
    return await this.service.createOrganizer({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Organizer)
  @nestAccessControl.UseRoles({
    resource: "Organizer",
    action: "update",
    possession: "any",
  })
  async updateOrganizer(
    @graphql.Args() args: UpdateOrganizerArgs
  ): Promise<Organizer | null> {
    try {
      return await this.service.updateOrganizer({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Organizer)
  @nestAccessControl.UseRoles({
    resource: "Organizer",
    action: "delete",
    possession: "any",
  })
  async deleteOrganizer(
    @graphql.Args() args: DeleteOrganizerArgs
  ): Promise<Organizer | null> {
    try {
      return await this.service.deleteOrganizer(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
